site_name: PulseView - Intellisails
site_url: https://intellisails.com

repo_name: intellisails/wiki
repo_url: https://github.com/intellisails

copyright: Copyright &copy; 2023 - 2024 intellisails.com

theme:
  name: material
  logo: img/logo.png
  favicon: img/logo.png
  features:
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to system preference

    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - css/extra.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - js/tablesort.js

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

nav:
- PulseView:
  - Introduction: 'index.md'
  - Kit Assembly: 'kit.md'
  - Download: 'download.md'
  - Install:
    - Preliminary : 'preliminary.md'
    - Lens installation : 'lens-installation.md'
    - First Start : 'first-start.md'
  - Recovery :
    - Recovery Mode: 'recovery-button.md'
    - Maskrom Mode: 'maskrom.md'
  - Software:
    - Cloudflare Calls: 'cloudflare-calls.md'
    - Tailscale: 'tailscale.md'
  - Hardware:
    - Overview: 'hardware.md'
    - Button: 'button.md'
    - Ethernet: 'ethernet.md'
    - USB: 'usb.md'
    - MIPI: 'mipi.md'
    - Iris: 'iris.md'
    - IR-CUT: 'ir-cut.md'
    - IR-LED: 'ir-led.md'
    - Audio: 'audio.md'
    - GPIO: 'gpio.md'
  - Troubleshooting: 'troubleshoot.md'
- Reddit:
  - Social media: 'social.md'
- Discord:
  - Social media: 'social.md'
- Github:
  - Social media: 'social.md'